feat: add tags `fzf-min-height`, `popup-min-size`
Aloxaf/fzf-tab pull request #320
Opened 2022-10-20 12:10 UTC by rekaerst

#

Add two new tags `fzf-min-height`, `popup-min-size`

| Tag            | Type   | Description                                |
| -------------- | ------ | ------------------------------------------ |
| fzf-min-height | int    | minimal height of fzf-tab widget           |
| popup-min-size | int[2] | minimal width and height of fzf-tmux-popup |

## use cases

Set a minimal size of fzf-tmux-popup window can prevent content from being
truncated by fzf preview window.

**default**
![image](https://user-images.githubusercontent.com/52642831/196944524-8369545b-ae82-4bcc-999d-eb15e15169c3.png)

**zstyle ':fzf-tab:*' popup-min-size 60 8**
![image](https://user-images.githubusercontent.com/52642831/196944434-712e1a85-f870-4f36-9369-ca3651f5d6d1.png)

2022-10-22 01:25 UTC, Aloxaf requested changes

2022-10-22 01:25 UTC, Aloxaf commented on lib/ftb-tmux-popup
> +echo $popup_min_size > /tmp/aaf
This line seems redundant?

2022-10-22 01:26 UTC, Aloxaf commented
the rest looks good to me

2022-10-22 01:38 UTC, rekaerst commented on lib/ftb-tmux-popup
> +echo $popup_min_size > /tmp/aaf
Yes. I forget to remove it.

2022-10-24 03:11 UTC, Aloxaf approved these changes

2022-10-24 03:12 UTC, merged

2022-10-24 03:12 UTC, Aloxaf commented
Thanks for your contribution!

BTW, don't forget to update wiki as well~